[server]
port = "8080" 
request_max_size = 100000000 # 100 MB

[blockchain]
node_wss = "wss://cronos-testnet-3.crypto.org:8546/"
contract_address = "0x40B24f2A0F58E050233A3C19eb42f297df069bB8"

[database]
database = "eykache"
user = "eykache"
password = "XXXXXXX"
host = "localhost"
port = 5432

[updater]
delay = 5 # 5 seconds